import { consonantLines as c, vowelLines as v } from "./lineDefs.js";
const consonants = {
  0: [],
  1: [c.lowerLeft, c.lowerRight],
  2: [c.lowerLeft, c.lowerRight, c.upperLeft],
  3: [
    c.lowerLeft,
    c.lowerRight,
    c.upperLeft,
    c.upperRight,
    c.lowerMiddle,
    c.upperMiddleBottom,
    c.upperMiddleTop,
  ],
  4: [c.lowerMiddle, c.upperMiddleBottom, c.upperRight],
  5: [c.lowerRight, c.lowerMiddle, c.upperMiddleBottom, c.upperMiddleTop],
  6: [c.lowerMiddle, c.upperMiddleBottom, c.upperLeft, c.upperRight],
  7: [c.upperMiddleTop, c.upperMiddleBottom, c.lowerLeft, c.lowerRight],
  8: [c.upperMiddleTop, c.upperMiddleBottom, c.lowerRight, c.upperRight],
  9: [c.lowerMiddle, c.lowerRight, c.upperMiddleBottom, c.upperRight],
  10: [c.upperMiddleTop, c.upperMiddleBottom, c.lowerLeft],
  11: [c.lowerMiddle, c.upperMiddleBottom, c.upperLeft],
  12: [c.lowerMiddle, c.lowerLeft, c.upperMiddleBottom, c.upperRight],
  13: [c.lowerRight, c.upperMiddleBottom, c.upperMiddleTop, c.upperLeft],
  14: [
    c.lowerMiddle,
    c.upperMiddleBottom,
    c.upperMiddleTop,
    c.upperLeft,
    c.upperRight,
  ],
  15: [
    c.lowerMiddle,
    c.lowerLeft,
    c.lowerRight,
    c.upperMiddleBottom,
    c.upperMiddleTop,
  ],
  16: [
    c.lowerMiddle,
    c.lowerLeft,
    c.upperMiddleBottom,
    c.upperMiddleTop,
    c.upperRight,
  ],
  17: [
    c.lowerMiddle,
    c.lowerRight,
    c.upperMiddleBottom,
    c.upperMiddleTop,
    c.upperLeft,
  ],
  18: [
    c.lowerMiddle,
    c.lowerLeft,
    c.lowerRight,
    c.upperMiddleBottom,
    c.upperLeft,
    c.upperRight,
  ],
  19: [
    c.lowerLeft,
    c.lowerRight,
    c.upperMiddleBottom,
    c.upperMiddleTop,
    c.upperLeft,
    c.upperRight,
  ],
  20: [c.lowerMiddle, c.lowerRight, c.upperMiddleBottom, c.upperMiddleTop],
  21: [c.lowerMiddle, c.upperMiddleBottom, c.upperMiddleTop, c.upperRight],
  22: [c.lowerMiddle, c.upperMiddleBottom, c.upperMiddleTop, c.upperLeft],
  23: [c.upperLeft, c.upperRight],
  24: [c.lowerMiddle, c.upperMiddleBottom, c.upperMiddleTop],
};

const vowels = {
  0: [],
  1: [v.middleBottom, v.middleTop, v.upperLeft, v.upperRight],
  2: [v.middleBottom, v.middleTop, v.upperLeft],
  3: [v.lowerLeft, v.lowerRight],
  4: [v.lowerLeft, v.lowerRight, v.middleBottom, v.middleTop],
  5: [v.lowerLeft, v.middleBottom, v.middleTop],
  6: [v.upperLeft, v.upperRight],
  7: [v.lowerRight, v.lowerLeft, v.middleBottom, v.middleTop, v.upperLeft],
  8: [v.lowerLeft, v.middleBottom, v.middleTop, v.upperLeft, v.upperRight],
  9: [v.lowerRight, v.lowerLeft, v.middleBottom, v.middleTop, v.upperRight],
  10: [v.lowerRight, v.middleBottom, v.middleTop, v.upperLeft, v.upperRight],
  11: [v.lowerRight, v.lowerLeft, v.upperLeft, v.upperRight],
  12: [v.lowerRight, v.middleBottom, v.middleTop, v.upperLeft],
  13: [v.upperLeft],
  14: [v.upperRight],
  15: [v.lowerLeft],
  16: [v.lowerRight],
  17: [
    v.lowerRight,
    v.lowerLeft,
    v.middleBottom,
    v.middleTop,
    v.upperLeft,
    v.upperRight,
  ],
  18: [v.lowerRight, v.middleBottom, v.middleTop],
};

export { consonants, vowels };
